import type { Product, WatchDesign } from "./types";

export type CollectionLine = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  indexBlurb: string;
  chapterTitle: string;
  image: string;
  ogImage: string;
  calibre: string;
  essay: string[];
  finishing: string;
};

export const photos = {
  ivory: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1600&q=80",
  gold: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=1600&q=80",
  black: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=1600&q=80",
  luxury: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1600&q=80",
  side: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1600&q=80",
  sport: "https://images.unsplash.com/photo-1594534475808-b41fb295b2d3?auto=format&fit=crop&w=1600&q=80",
  wrist: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&w=1600&q=80",
  bench: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=1600&q=80",
  movement: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=1600&q=80",
  classic: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=1600&q=80",
  silver: "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=1600&q=80",
  cinematic: "https://images.unsplash.com/photo-1609587312208-cea54be969e7?auto=format&fit=crop&w=2000&q=80",
};

export function watch(
  data: Omit<Product, "specGroups"> & { specGroups?: Product["specGroups"] },
): Product {
  const specGroups = data.specGroups ?? [
    {
      title: "Movement",
      rows: [
        { label: "Calibre", value: data.movement },
        { label: "Type", value: data.movementType },
        { label: "Power reserve", value: `${data.powerReserve} hours` },
      ],
    },
    {
      title: "Case",
      rows: [
        { label: "Material", value: data.material },
        { label: "Diameter", value: `${data.diameter} mm` },
        { label: "Thickness", value: `${data.thickness} mm` },
        { label: "Crystal", value: data.crystal },
        { label: "Water resistance", value: `${data.waterResistance} metres` },
      ],
    },
    {
      title: "Bracelet",
      rows: [{ label: "Bracelet / strap", value: data.bracelet }],
    },
  ];
  return { ...data, specGroups };
}

const steelChrono: WatchDesign = {
  caseMetal: "steel",
  dial: "#f3ead8",
  dialText: "#1a1814",
  markers: "baton",
  hands: "dauphine",
  bezel: "none",
  strap: "leather",
  strapColor: "#2a1f18",
  chronograph: true,
  dateWindow: true,
};

export const collectionLines: CollectionLine[] = [
  {
    slug: "heritage",
    name: "Heritage",
    tagline: "The original line",
    description: "The original line. Time-only, hand-finished, unchanged since 1924.",
    chapterTitle: "The first sentence.",
    indexBlurb:
      "Time-only enamel, extra-thin H-08, railroad minutes. Heritage is where the gold meridian was drawn first — and has not been redrawn since 1924.",
    image: photos.classic,
    ogImage: photos.classic,
    calibre: "H-08",
    finishing: "Enamel, extra-thin, railroad minutes",
    essay: [
      "Heritage is the first sentence the maison ever wrote. A thin case, an enamel dial, and the gold meridian drawn last — after the numerals have dried.",
      "These are watches for a quiet wrist. 34 to 40 millimetres, box sapphire, a calibre regulated until it agrees with Geneva.",
    ],
  },
  {
    slug: "chronograph",
    name: "Chronograph",
    tagline: "Measured time",
    description: "Measured time. Column-wheel construction, built for precision under pressure.",
    chapterTitle: "Three distinct events.",
    indexBlurb:
      "Column-wheel H-72. Start, stop, and reset as three mechanical sentences. Ivory opaline, blued hands, a tachymeter for those who still measure a road.",
    image: photos.ivory,
    ogImage: photos.ivory,
    calibre: "H-72",
    finishing: "Column wheel, three registers, tachymeter",
    essay: [
      "The start, the stop, and the reset should feel like three distinct mechanical events. That is why the H-72 is a column-wheel chronograph, not a cam.",
      "Ivory opaline, blued hands, a sapphire caseback. Chronograph One remains the maison’s most requested reference.",
    ],
  },
  {
    slug: "diver",
    name: "Diver",
    tagline: "Time at depth",
    description: "Time at depth. 300m water resistance, engineered for the sea.",
    chapterTitle: "Finished for the dark.",
    indexBlurb:
      "A diver finished like a dress watch. Ceramic bezel, lume that holds when the water is black, 200 to 500 metres — and the meridian still gold at 12.",
    image: photos.sport,
    ogImage: photos.sport,
    calibre: "H-90",
    finishing: "Ceramic bezel, 200–500 m, lume plots",
    essay: [
      "A diver that is finished like a dress watch. Alternating brushed and polished planes, a ceramic bezel that clicks with intent, lume you can still read when the water is black.",
      "Rated to 200 metres as a rule, 500 when the case asks for it. The meridian stays gold. Depth does not excuse a missing mark.",
    ],
  },
  {
    slug: "imperial",
    name: "Imperial",
    tagline: "Time in ceremony",
    description: "Time in ceremony. The Maison's dress collection, cased in precious metal.",
    chapterTitle: "Metal that remembers the lamp.",
    indexBlurb:
      "Yellow, rose, and white gold, and a black DLC that drinks the room. Numbered editions and moonphase — cases finished to be refinished by the next owner.",
    image: photos.gold,
    ogImage: photos.gold,
    calibre: "H-12",
    finishing: "18k gold, numbered editions, moonphase",
    essay: [
      "Imperial is the maison in metal that remembers the lamp. Yellow gold, rose, white, and a black DLC that drinks the room.",
      "Cases are finished to be refinished. The first owner is not the last. The meridian is designed to outlast both.",
    ],
  },
  {
    slug: "meridian",
    name: "Meridian",
    tagline: "Time in motion",
    description:
      "Time in motion. The line reimagined as a moving indication — our signature complication.",
    chapterTitle: "The line, carried.",
    indexBlurb:
      "GMT, dual time, worldtimer. HORLOGE is a French word for clock; this line carries the Geneva meridian around the world without moving the gold stroke at 12.",
    image: photos.black,
    ogImage: photos.black,
    calibre: "H-24",
    finishing: "GMT, worldtimer, dual time",
    essay: [
      "HORLOGE is a French word for clock. The maison’s mark is a meridian — the line by which a city agrees what hour it is.",
      "This line carries that agreement around the world: GMT, dual time, a worldtimer. The gold stroke at 12 is not decoration. It is the thesis.",
    ],
  },
];

export const products: Product[] = [
  watch({
    slug: "chronograph-one",
    name: "Chronograph One",
    reference: "H.72.40.IV",
    collection: "Chronograph",
    collectionSlug: "chronograph",
    price: 8900,
    novelty: true,
    tagline: "The signature three-register.",
    description:
      "A column-wheel chronograph with an ivory opaline dial, blued hands and a sapphire caseback. The maison’s most requested reference.",
    story:
      "Designed in 2018 as a modern reading of the 1947 timing watches used at Geneva motor clubs. The 40.5 mm case wears closer to 39 on the wrist.",
    diameter: 40.5,
    thickness: 13.2,
    waterResistance: 100,
    movement: "H-72 automatic chronograph",
    movementType: "Chronograph",
    powerReserve: 48,
    material: "Stainless steel",
    crystal: "Double-domed sapphire, AR coated",
    bracelet: "Hand-stitched alligator, steel pin buckle",
    complications: ["Chronograph", "Date", "Small seconds"],
    availability: "Available",
    images: [photos.ivory, photos.movement, photos.wrist, photos.side],
    design: steelChrono,
  }),
  watch({
    slug: "chronograph-dual",
    name: "Chronograph Dual",
    reference: "H.72.41.BK",
    collection: "Chronograph",
    collectionSlug: "chronograph",
    price: 9800,
    tagline: "Black opaline. Two counters.",
    description:
      "The Dual drops the running seconds for a cleaner bi-compax layout. A smoked black dial with silver subdials and a tachymeter rehaut.",
    story:
      "Requested by collectors who found the three-register too busy. The Dual is the atelier’s answer: timing, without the chatter.",
    diameter: 41,
    thickness: 13.4,
    waterResistance: 100,
    movement: "H-72D automatic chronograph",
    movementType: "Chronograph",
    powerReserve: 48,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Black alligator",
    complications: ["Chronograph", "Tachymeter"],
    availability: "In boutique",
    images: [photos.black, photos.side, photos.movement],
    design: {
      ...steelChrono,
      dial: "#161412",
      dialText: "#f4efe6",
      bezel: "tachymeter",
      strapColor: "#14110f",
    },
  }),
  watch({
    slug: "apex-sport",
    name: "Apex Sport",
    reference: "H.90.41.CER",
    collection: "Diver",
    collectionSlug: "diver",
    price: 12400,
    badge: "New",
    novelty: true,
    tagline: "Ceramic bezel. 70-hour reserve.",
    description:
      "A 41 mm sport watch with a unidirectional ceramic bezel, high-contrast dial and an integrated steel bracelet.",
    story:
      "Apex was developed with a sailing team in Brittany. The bezel clicks are deliberately loud. The bracelet tapers from 22 to 16 mm.",
    diameter: 41,
    thickness: 12.8,
    waterResistance: 200,
    movement: "H-90 automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Steel, ceramic bezel",
    crystal: "Sapphire, AR coated both sides",
    bracelet: "Integrated steel bracelet, folding clasp",
    complications: ["Date", "Unidirectional bezel"],
    availability: "Available",
    images: [photos.sport, photos.wrist, photos.side],
    design: {
      caseMetal: "steel",
      dial: "#12151c",
      dialText: "#f4efe6",
      markers: "baton",
      hands: "sport",
      bezel: "tachymeter",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      dateWindow: true,
    },
  }),
  watch({
    slug: "diver-300",
    name: "Diver 300",
    reference: "H.90.42.300",
    collection: "Diver",
    collectionSlug: "diver",
    price: 11200,
    tagline: "The professional diver.",
    description:
      "A 42 mm tool watch rated to 300 metres, with a helium escape valve, snowflake hands and a sandwich dial.",
    story:
      "Issued first to a Mediterranean survey crew. The lume plots are larger than the Heritage line by design — readability over elegance, though it has both.",
    diameter: 42,
    thickness: 14.1,
    waterResistance: 300,
    movement: "H-90D automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet, diving extension",
    complications: ["Date", "Unidirectional bezel", "Helium valve"],
    availability: "Available",
    images: [photos.silver, photos.sport, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#0b1c28",
      dialText: "#e8f0ea",
      markers: "dots",
      hands: "sport",
      bezel: "ceramic",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      dateWindow: true,
    },
  }),
  watch({
    slug: "velocity",
    name: "Velocity",
    reference: "H.90T.42.GR",
    collection: "Diver",
    collectionSlug: "diver",
    price: 13900,
    tagline: "Grade-5 titanium.",
    description:
      "A forest-green sandwich dial in a 42 mm titanium case. Light on the wrist, serious in the water.",
    story:
      "Velocity weighs 68 grams on a textile strap. It was the first HORLOGE case milled from grade-5 rather than grade-2 titanium.",
    diameter: 42,
    thickness: 13.6,
    waterResistance: 200,
    movement: "H-90T automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Grade-5 titanium",
    crystal: "Sapphire, AR coated",
    bracelet: "Woven textile, titanium buckle",
    complications: ["Date", "Ceramic bezel"],
    availability: "Available",
    images: [photos.side, photos.black, photos.wrist],
    design: {
      caseMetal: "black",
      dial: "#1e3a34",
      dialText: "#e8f0ea",
      markers: "dots",
      hands: "sport",
      bezel: "ceramic",
      strap: "nato",
      strapColor: "#1c2430",
      dateWindow: true,
    },
  }),
  watch({
    slug: "apex-gmt",
    name: "Apex GMT",
    reference: "H.90.41.GMT",
    collection: "Diver",
    collectionSlug: "diver",
    price: 14600,
    badge: "New",
    novelty: true,
    tagline: "Two time zones. One bezel.",
    description:
      "A true GMT with a jumping hour and a 24-hour ceramic bezel. Home time on the 24-hour hand, local time on the hour hand.",
    story:
      "Built for the maison’s boutique directors who live between Geneva, Paris and New York. The bezel is the same ceramic as Apex Sport.",
    diameter: 41,
    thickness: 13.0,
    waterResistance: 150,
    movement: "H-90G automatic GMT",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet",
    complications: ["GMT", "Date", "24-hour bezel"],
    availability: "In boutique",
    images: [photos.black, photos.sport, photos.luxury],
    design: {
      caseMetal: "steel",
      dial: "#10141c",
      dialText: "#f4efe6",
      markers: "baton",
      hands: "sport",
      bezel: "ceramic",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      dateWindow: true,
    },
  }),
  watch({
    slug: "heritage",
    name: "Heritage",
    reference: "H.08.36.EN",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 7400,
    tagline: "Railroad minutes. Modern heart.",
    description:
      "A 36 mm tribute to early maison pocket watches. Enamel-white dial, railroad chapter ring, heat-blued feuille hands.",
    story:
      "The Heritage is the only current reference that a watchmaker still fully assembles by hand, including the enamel firing.",
    diameter: 36,
    thickness: 9.4,
    waterResistance: 30,
    movement: "H-08 manual wind",
    movementType: "Manual",
    powerReserve: 38,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Honey calf, steel buckle",
    complications: ["Small seconds"],
    availability: "Available",
    images: [photos.classic, photos.ivory, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#f7f4ee",
      dialText: "#1c1a16",
      markers: "arabic",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#8a5a32",
      dateWindow: false,
    },
  }),
  watch({
    slug: "heritage-date",
    name: "Heritage Date",
    reference: "H.08.36.DT",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 7900,
    tagline: "The same enamel. A window for the day.",
    description:
      "Heritage, with a discreet date at 3 o’clock. For those who want the origin line on a working week.",
    story:
      "The date wheel is the same as Chronograph One, reduced. It is the most common first HORLOGE for new collectors.",
    diameter: 36,
    thickness: 9.8,
    waterResistance: 30,
    movement: "H-08D automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Black calf",
    complications: ["Date"],
    availability: "Available",
    images: [photos.ivory, photos.classic, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#f3ead8",
      dialText: "#1a1814",
      markers: "arabic",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#2a1f18",
      dateWindow: true,
    },
  }),
  watch({
    slug: "horizon-34",
    name: "Horizon 34",
    reference: "H.12.34.RG",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 9200,
    tagline: "Rose gold. A smaller wrist.",
    description:
      "A 34 mm extra-thin automatic in rose gold with a silver-grained dial. Designed to wear as easily with linen as with evening clothes.",
    story:
      "Horizon was drawn for the maison’s centenary as a unisex extra-thin. It is the thinnest cased watch HORLOGE currently makes.",
    diameter: 34,
    thickness: 7.9,
    waterResistance: 30,
    movement: "H-12 extra-thin automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k rose gold",
    crystal: "Box sapphire",
    bracelet: "Glazed alligator, rose gold buckle",
    complications: [],
    availability: "In boutique",
    images: [photos.gold, photos.classic, photos.luxury],
    design: {
      caseMetal: "rose",
      dial: "#efe6d6",
      dialText: "#3a2a12",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#5a3024",
      dateWindow: false,
    },
  }),
  watch({
    slug: "imperial-gold",
    name: "Imperial Gold",
    reference: "H.12.38.YG",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 24900,
    tagline: "Warm metal. Quiet authority.",
    description:
      "Eighteen-karat yellow gold, champagne sunray dial, applied Roman numerals. A dress watch meant to be inherited.",
    story:
      "Imperial Gold is finished with a fluted bezel cut in the same workshop as the 1930s pocket watches. Each case is numbered.",
    diameter: 38,
    thickness: 8.6,
    waterResistance: 50,
    movement: "H-12 extra-thin automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k yellow gold",
    crystal: "Box sapphire",
    bracelet: "Glazed alligator, gold buckle",
    complications: ["Date"],
    availability: "In boutique",
    images: [photos.gold, photos.luxury, photos.wrist],
    design: {
      caseMetal: "gold",
      dial: "#c5a46a",
      dialText: "#3a2a12",
      markers: "roman",
      hands: "dauphine",
      bezel: "fluted",
      strap: "leather",
      strapColor: "#3b2418",
      dateWindow: true,
    },
  }),
  watch({
    slug: "imperial-moon",
    name: "Imperial Moon",
    reference: "H.12.40.MN",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 28600,
    tagline: "A sky, under sapphire.",
    description:
      "A 40 mm moonphase in rose gold. The celestial disc is hand-painted; the stars are gold leaf.",
    story:
      "Moon was a 2024 novelty. Only 88 pieces are made each year. The moonphase is accurate to 122 years.",
    diameter: 40,
    thickness: 11.2,
    waterResistance: 30,
    movement: "H-12M automatic moonphase",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k rose gold",
    crystal: "Box sapphire",
    bracelet: "Midnight alligator",
    complications: ["Moonphase", "Date"],
    availability: "Waitlist",
    images: [photos.luxury, photos.gold, photos.movement],
    design: {
      caseMetal: "rose",
      dial: "#1a1520",
      dialText: "#e8d5a3",
      markers: "roman",
      hands: "dauphine",
      bezel: "fluted",
      strap: "leather",
      strapColor: "#1a1218",
      dateWindow: true,
    },
  }),
  watch({
    slug: "noir",
    name: "Noir",
    reference: "H.12G.39.AT",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 31900,
    limited: true,
    badge: "192 pcs",
    tagline: "Midnight, in gold.",
    description:
      "Black DLC over steel, a sunray midnight dial and yellow-gold dauphine hands. An atelier edition of 192 numbered pieces.",
    story:
      "When 192 are spoken for, the reference closes forever. The DLC is applied in Geneva; the gold hands are made in-house.",
    diameter: 39,
    thickness: 9.1,
    waterResistance: 50,
    movement: "H-12G automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "Steel, black DLC",
    crystal: "Double-domed sapphire",
    bracelet: "Black alligator",
    complications: ["Date"],
    availability: "Waitlist",
    images: [photos.luxury, photos.black, photos.cinematic],
    design: {
      caseMetal: "black",
      dial: "#0e1420",
      dialText: "#e8d5a3",
      markers: "baton",
      hands: "dauphine",
      bezel: "fluted",
      strap: "leather",
      strapColor: "#14110f",
      dateWindow: true,
    },
  }),
];

export const journal = [
  {
    slug: "the-meridian",
    title: "The Golden Meridian",
    date: "4 April 2026",
    category: "Identity",
    excerpt:
      "Every HORLOGE composition begins from twelve. A gold line, thinner than a hair, is the point from which the rest of the watch is built.",
    image: photos.cinematic,
    body: [
      "HORLOGE is a French word for clock. The maison’s mark is a meridian — the line by which a city agrees what hour it is. We draw it in gold, thinner than a hair, at 12 on every dial we make.",
      "The stroke is not applied after the watch is finished. It is the last act on the dial, and the first decision in the design. From that vertical, the chapter ring, the hands, the case, and the movement are composed outward.",
      "Gold, not printed ink. A line that will still read when the enamel has been lived with, when the first owner is not the last. Six would have been easier. Twelve is the hour a city names.",
      "You will find it on Heritage enamel and on a Diver 500. Depth does not excuse a missing mark. If it is absent, the watch is not ours.",
      "This note is not a manifesto for a logo. It is a workshop habit, written down so the next pair of hands knows where to begin.",
    ],
  },
  {
    slug: "inside-the-atelier",
    title: "Inside the Atelier",
    date: "12 March 2026",
    category: "Atelier",
    excerpt:
      "A HORLOGE watch passes through fewer than twelve pairs of hands before it leaves Geneva. The kiln sits eight metres from the casing bench, on purpose.",
    image: photos.bench,
    body: [
      "The atelier is not a factory. Cases are finished by hand. Movements are regulated individually, not by batch. This is slower than industrial watchmaking — deliberately so.",
      "Grand feu enamel is unforgiving. About four in ten dials crack in the kiln. The rest become Heritage. Dust, a draught, a slightly thick pour — any of these can ruin a day of work.",
      "We do not outsource this. The kiln sits eight metres from the casing bench, on purpose. Heat and casing should share a room, so a cracked dial never travels as if it were finished.",
      "A watch leaves those benches through fewer than twelve pairs of hands. One watchmaker owns it from casing to final timing. Their punch mark sits inside the caseback — ours, and theirs.",
      "The exploded drawing on the Craft page is a teaching calibre, HO-01. Wrist watches use H-08, H-72, H-90, H-12 and H-24. Do not confuse the study with the movement that leaves Geneva.",
    ],
  },
  {
    slug: "anatomy",
    title: "Anatomy of a Mechanical Watch",
    date: "2 February 2026",
    category: "Calibres",
    excerpt:
      "Case, crystal, dial, hands, movement. Opened in that order, then returned to silence. A short anatomy of how a HORLOGE is composed.",
    image: photos.movement,
    body: [
      "A mechanical watch is a small architecture. Opened in this order: case, crystal, dial, hands, movement — then returned to silence. The case holds the volume. The crystal admits light. The dial carries the meridian. The hands spend the hours. The movement is the reason any of it is true.",
      "The H-72 is a column-wheel chronograph because the start, stop and reset should feel like three distinct mechanical events — not like pressing a plastic shutter. Chronograph One still uses that architecture.",
      "Heritage keeps H-08 extra-thin. Diver keeps H-90, finished like a dress calibre even when the water is black. Imperial keeps H-12 for cases that will be refinished. Meridian keeps H-24 so a second hour can sit beside the gold stroke at 12.",
      "HO-01, drawn on the Craft page, is a teaching calibre — a concept architecture, not a production specification. Figures on a product sheet belong to the watch on the wrist.",
      "If you only remember one sequence: compose the meridian last on the dial, first in the design. Everything else is furniture around that line.",
    ],
  },
  {
    slug: "geneva-independent",
    title: "Geneva & Independent Horology",
    date: "19 January 2026",
    category: "Maison",
    excerpt:
      "Founded in Geneva in 1924. Still independent. No conglomerate owns our movements, our case designs, or our name.",
    image: photos.gold,
    body: [
      "The first bench sat on the Rue du Rhône, a room that still holds the same northern light. A lathe, a loupe, and the patience to treat the hour as a sentence.",
      "We remain an independent maison. No conglomerate owns our movements, our case designs, or our name. Each collection is developed in-house, in the same workshop the maison has occupied since 1924.",
      "Quartz arrived. We stayed mechanical. Regulation in five positions became a rule, not a brochure line. After-sales was written as a duty: a piece leaves Geneva once, and comes back for oil.",
      "Independence is not a mood. It is who may refuse a batch, who may scrap a dial, who may take fourteen days to agree with a rate. Those decisions stay in Geneva.",
      "The century is not a slogan on the Maison page. It is the same gold stroke, drawn last, on watches that will be refinished by owners we will not meet.",
    ],
  },
];

export const services = [
  {
    slug: "maintenance",
    title: "Complete service",
    duration: "8–12 weeks",
    body: "Full disassembly, cleaning, oiling, regulation in five positions, and a two-week timing check before the watch leaves Geneva.",
  },
  {
    slug: "polish",
    title: "Case & bracelet refresh",
    duration: "3 weeks",
    body: "Brushed surfaces stay brushed. Polished surfaces stay polished. We never drag a satin finish into a mirror by accident.",
  },
  {
    slug: "warranty",
    title: "International warranty",
    duration: "5 years",
    body: "Every HORLOGE is guaranteed against manufacturing defects for five years. Register your watch to extend courtesy movement care.",
  },
  {
    slug: "register",
    title: "Register your timepiece",
    duration: "Same day",
    body: "Enter your reference and the caseback number. We will attach the watch to your maison record for service and heritage.",
  },
];

export const quiz = [
  {
    key: "occasion",
    question: "How will you wear it most?",
    options: [
      { id: "everyday", label: "Every day", collections: ["Heritage", "Chronograph", "Meridian"] },
      { id: "water", label: "Near water, or in it", collections: ["Diver"] },
      { id: "evening", label: "Evenings and occasions", collections: ["Imperial", "Heritage"] },
      { id: "timing", label: "I like to time things", collections: ["Chronograph"] },
      { id: "travel", label: "I live in more than one city", collections: ["Meridian"] },
    ],
  },
  {
    key: "size",
    question: "What diameter feels right?",
    options: [
      { id: "small", label: "Under 37 mm", max: 37 },
      { id: "mid", label: "38–41 mm", min: 38, max: 41 },
      { id: "large", label: "42 mm and above", min: 42 },
    ],
  },
  {
    key: "metal",
    question: "Which metal are you drawn to?",
    options: [
      { id: "steel", label: "Steel", metals: ["steel"] },
      { id: "gold", label: "Yellow or rose gold", metals: ["gold", "rose"] },
      { id: "dark", label: "Titanium or black DLC", metals: ["black"] },
    ],
  },
];
