import { photos, watch } from "./catalog";
import type { Product, WatchDesign } from "./types";

const gmt: WatchDesign = {
  caseMetal: "steel",
  dial: "#101820",
  dialText: "#e8d5a3",
  markers: "baton",
  hands: "sport",
  bezel: "ceramic",
  strap: "bracelet",
  strapColor: "#c5c7ca",
  dateWindow: true,
};

export const extraProducts: Product[] = [
  watch({
    slug: "heritage-seconds",
    name: "Heritage Small Seconds",
    reference: "H.08.38.SS",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 8100,
    tagline: "A seconds register, kept quiet.",
    description:
      "The 38 mm Heritage with a sub-seconds at 6. Enamel dial, railroad minutes, and the maison’s gold meridian at 12.",
    story: "Drawn for collectors who wanted Heritage proportions with a more classical layout than the Date.",
    diameter: 38,
    thickness: 9.6,
    waterResistance: 30,
    movement: "H-08S manual wind",
    movementType: "Manual",
    powerReserve: 38,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Cognac calf",
    complications: ["Small seconds"],
    availability: "Available",
    images: [photos.classic, photos.ivory, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#f7f4ee",
      dialText: "#1c1a16",
      markers: "arabic",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#8a5a32",
    },
  }),
  watch({
    slug: "heritage-salmon",
    name: "Heritage Salmon",
    reference: "H.08.36.SA",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 8600,
    novelty: true,
    badge: "New",
    tagline: "A dial the colour of evening light.",
    description:
      "Grand feu salmon enamel on the 36 mm Heritage. Applied indexes, blued hands, and a heat-blued seconds.",
    story: "Only 80 salmon dials leave the kiln each year. The rest crack. That is the point.",
    diameter: 36,
    thickness: 9.4,
    waterResistance: 30,
    movement: "H-08 automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Burgundy alligator",
    complications: ["Date"],
    availability: "In boutique",
    images: [photos.gold, photos.classic, photos.ivory],
    design: {
      caseMetal: "steel",
      dial: "#d4a090",
      dialText: "#3a2418",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#5a2418",
      dateWindow: true,
    },
  }),
  watch({
    slug: "heritage-duo",
    name: "Heritage Duo",
    reference: "H.08.40.DT",
    collection: "Heritage",
    collectionSlug: "heritage",
    price: 9400,
    tagline: "Two time zones, still a dress watch.",
    description:
      "A 40 mm extra-thin dual time with a discreet 24-hour ring. For the collector who travels without wanting a tool watch.",
    story: "The second hour hand is skeletonised so the dial stays quiet. Local time is still the loudest voice.",
    diameter: 40,
    thickness: 10.2,
    waterResistance: 50,
    movement: "H-08G automatic GMT",
    movementType: "Automatic",
    powerReserve: 42,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Navy alligator",
    complications: ["GMT", "Date"],
    availability: "Available",
    images: [photos.ivory, photos.silver, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#e8e2d4",
      dialText: "#1a1814",
      markers: "roman",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#1c2430",
      dateWindow: true,
    },
  }),
  watch({
    slug: "chrono-gold",
    name: "Chronograph Or",
    reference: "H.72.40.YG",
    collection: "Chronograph",
    collectionSlug: "chronograph",
    price: 22800,
    tagline: "The signature, in yellow gold.",
    description:
      "Chronograph One’s three-register layout in 18k yellow gold, champagne subdials, and a glazed alligator strap.",
    story: "The gold chrono is a boutique piece. It is not listed in every catalogue on purpose.",
    diameter: 40.5,
    thickness: 13.2,
    waterResistance: 50,
    movement: "H-72 automatic chronograph",
    movementType: "Chronograph",
    powerReserve: 48,
    material: "18k yellow gold",
    crystal: "Double-domed sapphire",
    bracelet: "Glazed alligator, gold buckle",
    complications: ["Chronograph", "Date"],
    availability: "In boutique",
    images: [photos.gold, photos.luxury, photos.movement],
    design: {
      caseMetal: "gold",
      dial: "#f3ead8",
      dialText: "#3a2a12",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#3b2418",
      chronograph: true,
      dateWindow: true,
    },
  }),
  watch({
    slug: "chrono-compact",
    name: "Chronograph Compact",
    reference: "H.72.38.IV",
    collection: "Chronograph",
    collectionSlug: "chronograph",
    price: 9200,
    tagline: "The same calibre. A smaller wrist.",
    description: "A 38 mm reading of Chronograph One. Ivory dial, two counters, no compromise on the column wheel.",
    story: "Requested so often we stopped saying no. The Compact is now a permanent reference.",
    diameter: 38,
    thickness: 12.8,
    waterResistance: 100,
    movement: "H-72 automatic chronograph",
    movementType: "Chronograph",
    powerReserve: 48,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Black alligator",
    complications: ["Chronograph", "Date"],
    availability: "Available",
    images: [photos.ivory, photos.classic, photos.side],
    design: {
      caseMetal: "steel",
      dial: "#f3ead8",
      dialText: "#1a1814",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#14110f",
      chronograph: true,
      dateWindow: true,
    },
  }),
  watch({
    slug: "chrono-racing",
    name: "Chronograph Racing",
    reference: "H.72.42.RC",
    collection: "Chronograph",
    collectionSlug: "chronograph",
    price: 11800,
    badge: "New",
    novelty: true,
    tagline: "Tachymeter. Panda. Purpose.",
    description:
      "A 42 mm racing chrono with a white panda dial, black subdials and an engraved tachymeter bezel.",
    story: "Named for the 1947 Geneva club watches, not for a sponsorship. There is no team. There is a scale.",
    diameter: 42,
    thickness: 14.0,
    waterResistance: 100,
    movement: "H-72R automatic chronograph",
    movementType: "Chronograph",
    powerReserve: 48,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet",
    complications: ["Chronograph", "Tachymeter"],
    availability: "Available",
    images: [photos.silver, photos.sport, photos.side],
    design: {
      caseMetal: "steel",
      dial: "#f4efe6",
      dialText: "#121212",
      markers: "baton",
      hands: "sport",
      bezel: "tachymeter",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      chronograph: true,
      dateWindow: true,
    },
  }),
  watch({
    slug: "diver-500",
    name: "Diver 500",
    reference: "H.90.44.500",
    collection: "Diver",
    collectionSlug: "diver",
    price: 15800,
    tagline: "The professional, taken further.",
    description: "A 44 mm diver rated to 500 metres, with a helium valve, ceramic bezel and a locking crown.",
    story: "Issued to a North Sea survey. The extension clasp is the same as Diver 300, scaled.",
    diameter: 44,
    thickness: 15.2,
    waterResistance: 500,
    movement: "H-90X automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated, 2.2 mm",
    bracelet: "Steel bracelet, diving extension",
    complications: ["Date", "Unidirectional bezel", "Helium valve"],
    availability: "Available",
    images: [photos.sport, photos.silver, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#061018",
      dialText: "#e8f0ea",
      markers: "dots",
      hands: "sport",
      bezel: "ceramic",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      dateWindow: true,
    },
  }),
  watch({
    slug: "diver-compact",
    name: "Diver 39",
    reference: "H.90.39.BL",
    collection: "Diver",
    collectionSlug: "diver",
    price: 10800,
    tagline: "Depth, in a smaller case.",
    description: "A 39 mm diver in steel with a sunray blue dial. 200 metres, ceramic bezel, still a tool.",
    story: "For wrists that found 42 mm honest but heavy. The Diver 39 is the one most often seen in the city.",
    diameter: 39,
    thickness: 12.4,
    waterResistance: 200,
    movement: "H-90 automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet",
    complications: ["Date", "Unidirectional bezel"],
    availability: "Available",
    images: [photos.silver, photos.black, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#12344a",
      dialText: "#f4efe6",
      markers: "baton",
      hands: "sport",
      bezel: "ceramic",
      strap: "bracelet",
      strapColor: "#c5c7ca",
      dateWindow: true,
    },
  }),
  watch({
    slug: "apex-bronze",
    name: "Apex Bronze",
    reference: "H.90.41.BR",
    collection: "Diver",
    collectionSlug: "diver",
    price: 13200,
    novelty: true,
    tagline: "A case that will keep changing.",
    description:
      "Aluminium-bronze that patinas. A tropical dial, ceramic bezel, and a tropic rubber strap.",
    story: "Bronze was resisted internally for years. Then a client wore a prototype for a summer. The argument ended.",
    diameter: 41,
    thickness: 13.1,
    waterResistance: 200,
    movement: "H-90 automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Aluminium bronze",
    crystal: "Sapphire, AR coated",
    bracelet: "Tropic rubber, bronze buckle",
    complications: ["Date", "Unidirectional bezel"],
    availability: "In boutique",
    images: [photos.gold, photos.sport, photos.side],
    design: {
      caseMetal: "gold",
      dial: "#3a2a18",
      dialText: "#e8d5a3",
      markers: "dots",
      hands: "sport",
      bezel: "ceramic",
      strap: "nato",
      strapColor: "#2a1f14",
      dateWindow: true,
    },
  }),
  watch({
    slug: "imperial-white",
    name: "Imperial White Gold",
    reference: "H.12.38.WG",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 26800,
    tagline: "Cooler metal. Same silence.",
    description: "18k white gold, silver-grained dial, diamond indexes at 12, 3, 6 and 9. The dress watch in winter light.",
    story: "White gold Imperial is the one most often chosen as a second piece, after steel Heritage.",
    diameter: 38,
    thickness: 8.6,
    waterResistance: 50,
    movement: "H-12 extra-thin automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k white gold",
    crystal: "Box sapphire",
    bracelet: "Grey alligator, white gold buckle",
    complications: ["Date"],
    availability: "In boutique",
    images: [photos.luxury, photos.silver, photos.classic],
    design: {
      caseMetal: "steel",
      dial: "#ece8e0",
      dialText: "#2a2a2c",
      markers: "roman",
      hands: "dauphine",
      bezel: "fluted",
      strap: "leather",
      strapColor: "#3a3a40",
      dateWindow: true,
    },
  }),
  watch({
    slug: "imperial-day",
    name: "Imperial Day-Date",
    reference: "H.12.40.DD",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 29400,
    tagline: "The day, written in full.",
    description: "A 40 mm day-date in yellow gold. The day window is English; other languages on request.",
    story: "The day disc is the same diameter as the moonphase disc in Imperial Moon. That is not an accident.",
    diameter: 40,
    thickness: 10.8,
    waterResistance: 50,
    movement: "H-12DD automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k yellow gold",
    crystal: "Box sapphire",
    bracelet: "Gold bracelet, hidden clasp",
    complications: ["Day-Date"],
    availability: "Waitlist",
    images: [photos.gold, photos.luxury, photos.cinematic],
    design: {
      caseMetal: "gold",
      dial: "#c5a46a",
      dialText: "#3a2a12",
      markers: "roman",
      hands: "dauphine",
      bezel: "fluted",
      strap: "bracelet",
      strapColor: "#e0c070",
      dateWindow: true,
    },
  }),
  watch({
    slug: "imperial-open",
    name: "Imperial Ouverte",
    reference: "H.12.39.SK",
    collection: "Imperial",
    collectionSlug: "imperial",
    price: 34500,
    limited: true,
    badge: "88 pcs",
    tagline: "The calibre, allowed to speak.",
    description: "An open-worked 39 mm Imperial. The H-12 is skeletonised by hand; the meridian remains gold.",
    story: "Eighty-eight pieces. The anglage on the bridges is the longest operation in the atelier.",
    diameter: 39,
    thickness: 9.4,
    waterResistance: 30,
    movement: "H-12S skeleton automatic",
    movementType: "Automatic",
    powerReserve: 42,
    material: "18k rose gold",
    crystal: "Double-domed sapphire, front and back",
    bracelet: "Black alligator",
    complications: ["Skeleton"],
    availability: "Waitlist",
    images: [photos.movement, photos.luxury, photos.gold],
    design: {
      caseMetal: "rose",
      dial: "#2a1814",
      dialText: "#e8d5a3",
      markers: "baton",
      hands: "dauphine",
      bezel: "fluted",
      strap: "leather",
      strapColor: "#14110f",
    },
  }),
  watch({
    slug: "meridian-gmt",
    name: "Meridian GMT",
    reference: "H.24.41.GMT",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 15200,
    novelty: true,
    badge: "New",
    tagline: "Home, and wherever you are.",
    description:
      "The namesake line. A true GMT with a jumping hour, 24-hour ceramic bezel, and the gold meridian at 12.",
    story:
      "HORLOGE is named for the clock. Meridian is named for the line. This is the watch the maison should have made first.",
    diameter: 41,
    thickness: 13.0,
    waterResistance: 150,
    movement: "H-24 automatic GMT",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet",
    complications: ["GMT", "Date", "24-hour bezel"],
    availability: "Available",
    images: [photos.black, photos.sport, photos.wrist],
    design: gmt,
  }),
  watch({
    slug: "meridian-world",
    name: "Meridian Worldtimer",
    reference: "H.24.42.WT",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 18600,
    tagline: "Twenty-four cities, one crown.",
    description:
      "A 42 mm worldtimer with a city disc and 24-hour ring. Geneva sits at the top, as it should.",
    story: "The city disc is printed in the same type as the maison’s 1924 ledgers. We checked.",
    diameter: 42,
    thickness: 13.8,
    waterResistance: 100,
    movement: "H-24W automatic worldtimer",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Black alligator",
    complications: ["Worldtimer", "Date"],
    availability: "In boutique",
    images: [photos.cinematic, photos.black, photos.luxury],
    design: {
      ...gmt,
      dial: "#0e1420",
      strap: "leather",
      strapColor: "#14110f",
      bezel: "none",
    },
  }),
  watch({
    slug: "meridian-pilot",
    name: "Meridian Pilot",
    reference: "H.24.43.PL",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 16400,
    tagline: "A large triangle at 12. On purpose.",
    description: "A 43 mm pilot with cathedral hands, a railroad inner ring, and a lockable crown at 3.",
    story: "Not a licensed cockpit watch. A watch a pilot would actually read. That is a different brief.",
    diameter: 43,
    thickness: 13.5,
    waterResistance: 100,
    movement: "H-24P automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Calf, long tail",
    complications: ["Date"],
    availability: "Available",
    images: [photos.side, photos.sport, photos.black],
    design: {
      caseMetal: "steel",
      dial: "#1a1a16",
      dialText: "#f4efe6",
      markers: "arabic",
      hands: "sword",
      bezel: "none",
      strap: "leather",
      strapColor: "#2a1f18",
      dateWindow: true,
    },
  }),
  watch({
    slug: "meridian-night",
    name: "Meridian Overnight",
    reference: "H.24.40.NT",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 17200,
    tagline: "For the hours that are not local.",
    description: "A 40 mm dual time with a night-and-day indicator and a smoked sapphire caseback.",
    story: "Designed for the boutique directors who live between Geneva and New York. Home time is always Geneva.",
    diameter: 40,
    thickness: 12.2,
    waterResistance: 100,
    movement: "H-24N automatic",
    movementType: "Automatic",
    powerReserve: 70,
    material: "Stainless steel",
    crystal: "Sapphire, AR coated",
    bracelet: "Steel bracelet",
    complications: ["GMT", "Day/night"],
    availability: "Available",
    images: [photos.black, photos.cinematic, photos.wrist],
    design: {
      ...gmt,
      dial: "#12151c",
    },
  }),
  watch({
    slug: "meridian-compact",
    name: "Meridian 36",
    reference: "H.24.36.IV",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 12800,
    tagline: "Two zones, a smaller wrist.",
    description: "The Meridian idea at 36 mm. Ivory dial, gold dual-time hand, no bezel. A GMT you can wear with linen.",
    story: "Proof that a travel watch does not have to look like equipment.",
    diameter: 36,
    thickness: 10.4,
    waterResistance: 50,
    movement: "H-24C automatic GMT",
    movementType: "Automatic",
    powerReserve: 42,
    material: "Stainless steel",
    crystal: "Box sapphire",
    bracelet: "Ivory calf",
    complications: ["GMT", "Date"],
    availability: "Available",
    images: [photos.ivory, photos.classic, photos.wrist],
    design: {
      caseMetal: "steel",
      dial: "#f3ead8",
      dialText: "#1a1814",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "leather",
      strapColor: "#c4b49a",
      dateWindow: true,
    },
  }),
  watch({
    slug: "meridian-gold",
    name: "Meridian Or",
    reference: "H.24.40.YG",
    collection: "Meridian",
    collectionSlug: "meridian",
    price: 31200,
    limited: true,
    badge: "64 pcs",
    tagline: "The line, in yellow gold.",
    description: "A 40 mm yellow-gold GMT. Champagne dial, 24-hour chapter, and a gold bracelet that tapers to 16 mm.",
    story: "Sixty-four pieces — one for each tooth on the first H-24 ratchet wheel.",
    diameter: 40,
    thickness: 12.0,
    waterResistance: 50,
    movement: "H-24 automatic GMT",
    movementType: "Automatic",
    powerReserve: 70,
    material: "18k yellow gold",
    crystal: "Sapphire, AR coated",
    bracelet: "Gold bracelet",
    complications: ["GMT", "Date"],
    availability: "Waitlist",
    images: [photos.gold, photos.luxury, photos.cinematic],
    design: {
      caseMetal: "gold",
      dial: "#c5a46a",
      dialText: "#3a2a12",
      markers: "baton",
      hands: "dauphine",
      bezel: "none",
      strap: "bracelet",
      strapColor: "#e0c070",
      dateWindow: true,
    },
  }),
];
